---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

scenario:
  name: ci
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy

dependency:
  name: galaxy
  options:
    role-file: ../../../galaxy-requirements.yml
    requirements-file: ../../../galaxy-requirements.yml
driver:
  name: gce
  project_id: pure-faculty-367518
  region: us-central1
  auth_kind: serviceaccount
  username: $USER
  service_account_file: $GOOGLE_JSON_KEY_LOCATION
  external_access: true
  instance_os_type: linux
lint: |
  set -e
  PATH=${PATH}
  yamllint -c ../../../.yaml-lint.yml .
  ansible-lint -v -c ../../../.ansible-lint
platforms:
  - name: int-jammy-vm-$POSFIX_NAME
    zone: us-central1-c
    machine_type: e2-standard-16
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
    tags:
      items:
        - allow-ssh
    disks:
      - auto_delete: true
        boot: true
        type: PERSISTENT
        initialize_params:
          source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
          disk_size_gb: 50  # Boot disk size
      - auto_delete: true
        boot: false
        type: PERSISTENT
        initialize_params:
          disk_name: extra-disk-$POSFIX_NAME
          disk_size_gb: 100  # Additional disk size
          disk_type: pd-ssd  # or pd-standard
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PROJECT_DIRECTORY}/../kpt/molecule/default/prepare.yml
    converge: ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/converge.yml
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/../../../playbooks/library
verifier:
  name: testinfra
  directory: ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/tests
